DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS movements;
DROP TABLE IF EXISTS amountCategory;
DROP TABLE IF EXISTS vaults;
DROP TABLE IF EXISTS storeAccess;
DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS rols;